"""
Building Dimension Extraction Module

This module provides functionality to extract building dimensions from images
using depth maps generated by MiDaS or similar depth estimation models.
"""

import cv2
import numpy as np
import json
from typing import Dict, List, Tuple, Optional, Any
from dataclasses import dataclass, asdict


@dataclass
class BuildingDimensions:
    """Data class to store building dimensions."""
    width_meters: float
    height_meters: float
    depth_meters: float
    area_square_meters: float
    volume_cubic_meters: float
    confidence: float
    metadata: Dict[str, Any]
    
    def to_json(self) -> str:
        """Convert dimensions to JSON string."""
        return json.dumps(asdict(self), indent=2)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert dimensions to dictionary."""
        return asdict(self)


class DimensionExtractor:
    """
    Extract building dimensions from images and depth maps.
    """
    
    def __init__(self, reference_distance: Optional[float] = None):
        """
        Initialize the dimension extractor.
        
        Args:
            reference_distance: Known distance to a reference point in meters.
                              If None, relative measurements are used.
        """
        self.reference_distance = reference_distance
    
    def extract_dimensions(
        self,
        image: np.ndarray,
        depth_map: np.ndarray,
        reference_pixel: Optional[Tuple[int, int]] = None
    ) -> BuildingDimensions:
        """
        Extract building dimensions from an image and its depth map.
        
        Args:
            image: Input image as numpy array (BGR format)
            depth_map: Corresponding depth map as numpy array
            reference_pixel: Optional pixel coordinates of a reference point with known distance
        
        Returns:
            BuildingDimensions object containing extracted dimensions
        """
        # Ensure depth map is normalized
        if depth_map.dtype != np.float32:
            depth_map = depth_map.astype(np.float32)
        
        # Normalize depth map to 0-1 range
        depth_normalized = cv2.normalize(depth_map, None, 0, 1, cv2.NORM_MINMAX)
        
        # Detect building edges
        edges = self._detect_building_edges(image)
        
        # Find building contours
        contours = self._find_building_contours(edges)
        
        if not contours:
            # Return default values if no building detected
            return BuildingDimensions(
                width_meters=0.0,
                height_meters=0.0,
                depth_meters=0.0,
                area_square_meters=0.0,
                volume_cubic_meters=0.0,
                confidence=0.0,
                metadata={"status": "no_building_detected"}
            )
        
        # Get the largest contour (assumed to be the main building)
        main_contour = max(contours, key=cv2.contourArea)
        
        # Calculate dimensions
        dimensions = self._calculate_dimensions(
            main_contour, depth_normalized, image.shape, reference_pixel
        )
        
        return dimensions
    
    def _detect_building_edges(self, image: np.ndarray) -> np.ndarray:
        """Detect edges in the image to identify building boundaries."""
        # Convert to grayscale
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        
        # Apply Gaussian blur to reduce noise
        blurred = cv2.GaussianBlur(gray, (5, 5), 0)
        
        # Use Canny edge detection
        edges = cv2.Canny(blurred, 50, 150)
        
        return edges
    
    def _find_building_contours(self, edges: np.ndarray) -> List[np.ndarray]:
        """Find contours representing building structures."""
        # Find contours
        contours, _ = cv2.findContours(
            edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
        )
        
        # Filter contours by area (remove small noise)
        min_area = edges.shape[0] * edges.shape[1] * 0.01  # At least 1% of image
        filtered_contours = [
            cnt for cnt in contours if cv2.contourArea(cnt) > min_area
        ]
        
        return filtered_contours
    
    def _calculate_dimensions(
        self,
        contour: np.ndarray,
        depth_map: np.ndarray,
        image_shape: Tuple[int, ...],
        reference_pixel: Optional[Tuple[int, int]]
    ) -> BuildingDimensions:
        """Calculate building dimensions from contour and depth information."""
        # Get bounding rectangle
        x, y, w, h = cv2.boundingRect(contour)
        
        # Extract depth values for the building region
        building_depth = depth_map[y:y+h, x:x+w]
        avg_depth = np.mean(building_depth)
        min_depth = np.min(building_depth)
        max_depth = np.max(building_depth)
        
        # Calculate scaling factor
        if self.reference_distance and reference_pixel:
            ref_x, ref_y = reference_pixel
            ref_depth = depth_map[ref_y, ref_x]
            scale_factor = self.reference_distance / ref_depth if ref_depth > 0 else 1.0
        else:
            # Use a default scale based on typical building photography
            # Assume average depth of 1.0 corresponds to 10 meters
            scale_factor = 10.0
        
        # Calculate dimensions in meters
        # Width and height in pixels converted to meters using depth-based scaling
        depth_scale = avg_depth * scale_factor
        
        # Estimate real-world dimensions
        # Pixel dimensions adjusted by depth for perspective
        width_meters = (w / image_shape[1]) * depth_scale * 2
        height_meters = (h / image_shape[0]) * depth_scale * 2
        depth_meters = (max_depth - min_depth) * scale_factor
        
        # Calculate area and volume
        area_square_meters = width_meters * height_meters
        volume_cubic_meters = area_square_meters * depth_meters
        
        # Calculate confidence based on contour quality
        contour_area = cv2.contourArea(contour)
        bbox_area = w * h
        confidence = contour_area / bbox_area if bbox_area > 0 else 0.0
        
        return BuildingDimensions(
            width_meters=round(width_meters, 2),
            height_meters=round(height_meters, 2),
            depth_meters=round(depth_meters, 2),
            area_square_meters=round(area_square_meters, 2),
            volume_cubic_meters=round(volume_cubic_meters, 2),
            confidence=round(confidence, 3),
            metadata={
                "bounding_box": {"x": int(x), "y": int(y), "width": int(w), "height": int(h)},
                "depth_statistics": {
                    "average": round(float(avg_depth), 3),
                    "min": round(float(min_depth), 3),
                    "max": round(float(max_depth), 3)
                },
                "scale_factor": round(scale_factor, 3)
            }
        )


def process_building_images(
    image_paths: List[str],
    depth_map_paths: List[str],
    output_json_path: str = "building_dimensions.json"
) -> List[BuildingDimensions]:
    """
    Process multiple building images and extract dimensions.
    
    Args:
        image_paths: List of paths to building images
        depth_map_paths: List of paths to corresponding depth maps
        output_json_path: Path to save the JSON output
    
    Returns:
        List of BuildingDimensions objects
    """
    if len(image_paths) != len(depth_map_paths):
        raise ValueError("Number of images must match number of depth maps")
    
    extractor = DimensionExtractor()
    all_dimensions = []
    
    for img_path, depth_path in zip(image_paths, depth_map_paths):
        # Load image and depth map
        image = cv2.imread(img_path)
        depth_map = cv2.imread(depth_path, cv2.IMREAD_GRAYSCALE)
        
        if image is None or depth_map is None:
            print(f"Warning: Could not load {img_path} or {depth_path}")
            continue
        
        # Extract dimensions
        dimensions = extractor.extract_dimensions(image, depth_map)
        all_dimensions.append(dimensions)
    
    # Save to JSON
    output_data = {
        "buildings": [dim.to_dict() for dim in all_dimensions],
        "total_buildings": len(all_dimensions)
    }
    
    with open(output_json_path, 'w') as f:
        json.dump(output_data, f, indent=2)
    
    print(f"Saved dimensions to {output_json_path}")
    
    return all_dimensions
